### ISSUE TITLE
🐛 BUG: cannot initialize lsp

### ISSUE THREAD

**Issue by JimitSoni18** [withastro/language-tools#767]
### Describe the Bug

I am using helix editor with lsp installed and with --stdio arg, and it appears that the astro sever fails to start, giving the following error: `failed to initialize language server: protocol error: InternalError: Request initialize failed with message: Cannot read properties of undefined (reading 'cancellationPipeName')`

the full rpc log is below:
`
2024-02-04T22:25:10.786 helix_lsp::transport [INFO] astro-ls -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"positionEncodings":["utf-8","utf-32","utf-16"]},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"isPreferredSupport":true,"resolveSupport":{"properties":["edit","command"]}},"completion":{"completionItem":{"deprecatedSupport":true,"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"inlayHint":{"dynamicRegistration":false},"publishDiagnostics":{"versionSupport":true},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":true},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":false},"executeCommand":{"dynamicRegistration":false},"inlayHint":{"refreshSupport":false},"symbol":{"dynamicRegistration":false},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort","normalizesLineEndings":false,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"helix","version":"23.10 (f6021dd0)"},"processId":163991,"rootPath":"/home/jimit/Programming/Lang/JS/portfolio","rootUri":"file:///home/jimit/Programming/Lang/JS/portfolio","workspaceFolders":[{"name":"portfolio","uri":"file:///home/jimit/Programming/Lang/JS/portfolio"}]},"id":0}
2024-02-04T22:25:11.102 helix_lsp::transport [INFO] astro-ls <- {"jsonrpc":"2.0","id":0,"error":{"code":-32603,"message":"Request initialize failed with message: Cannot read properties of undefined (reading 'cancellationPipeName')"}}
2024-02-04T22:25:11.102 helix_lsp::transport [ERROR] astro-ls <- InternalError: Request initialize failed with message: Cannot read properties of undefined (reading 'cancellationPipeName')
2024-02-04T22:25:11.102 helix_lsp [ERROR] failed to initialize language server: protocol error: InternalError: Request initialize failed with message: Cannot read properties of undefined (reading 'cancellationPipeName')
`

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. npm i -g @astro/language-server
3. add astro lsp config to your favourite editor
4. start working on .astro file
5. Error!

**Comment by schelmo** [comment]
i'm using the [ts plugin](https://www.npmjs.com/package/@astrojs/ts-plugin) with the `typescript-language-server` in helix. works very well.
my `languages.toml`:
```toml
[language-server.typescript-language-server.config.typescript]
tsdk = "/usr/lib/node_modules/typescript/lib"

[[language-server.typescript-language-server.config.plugins]]
name = "@astrojs/ts-plugin"
location = "/usr/lib/node_modules/@astrojs/ts-plugin"
languages = [ "astro" ]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/usr/lib/node_modules/@vue/typescript-plugin"
languages = [ "vue" ]

[[language]]
name = "astro"
roots = ["package.json", "astro.config.ts"]
language-servers = [ "typescript-language-server" ]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "astro"] }

[[language]]
name = "vue"
formatter = { command = "prettier", args = ["--parser", "vue"] }
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server"]
```
(you probably have to adjust the paths)
the advantage: you only have one lsp running for ts/js/vue/astro
