### ISSUE TITLE
🐛 BUG: Astro emmet completions broken with 2.12.8 update, does not offer correct auto complete

### ISSUE THREAD

**Issue by davidjost** [withastro/language-tools#921]
### Describe the Bug

I was writing CSS in astro when the VScode extension update showed, updated it, immediately after the auto completions were broken.

**Expected behavior**
Typing `ttu` offers and autocompletes to: `text-transform: uppercase;`

**Current behavior in v2.12.8**
Typing `ttu` offers `text-underline-offset` and autocompletes to `ttext-underline-offset: ;` (including extra `t`)

This goes for all CSS suggestions. HTML emmet seems to be working fine so far.

**Comment by Princesseuh** [comment]
Could you share a full file where this happens?

**Comment by davidjost** [comment]
It definitely is file related, I can't share this file specifically. I have tracked the issue in a test file with 8 imports, 170 lines of html, css:gobal, css and empty script tag, see gif.

Emmet shows in the global css scope and does not in the local scope. 

I can't reproduce the behavior in a new file with the same structure, it works as it should with emmet offered in both scopes.

![Jul-26-2024 17-16-59](https://github.com/user-attachments/assets/10e60eb6-c526-47a1-b9cd-6a9bfcfc24d0)

**Comment by davidjost** [comment]
I have tracked the issue to an emoji used in a `<style is:global>` block that sits in an inline svg declaration.
```css
<style is:global>
  .logo:hover {
    cursor: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='40' height='48' viewport='0 0 100 100' style='fill:black;font-size:2em;'><text y='70%'>😎</text></svg>") 16 0, auto;
    filter: brightness(220%) saturate(200%) drop-shadow(0px 0px 2px teal) drop-shadow(var(--value) var(--value) 0 oklch(var(--color-accent-20))) drop-shadow(var(--calc) var(--calc) 0 oklch(var(--color-accent-30)));
  }
</style>
```

Removing the emoji solves the issue.

![Uploading Jul-30-2024 16-36-02.gif…]()
